// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class RaporFonksiyonu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RaporFonksiyonu));
        
        string IMigrationMetadata.Id
        {
            get { return "202409171724122_RaporFonksiyonu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
